---
title: "P8157 - Final Project"
author: "Joe LaRocca"
date: "2025-11-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(lme4)
library(nlme)
library(geepack)
library(survival)
library(tidyverse)
library(flextable)
library(cowplot)

```

## Part 1: Upload and Clean Data

```{r}

pbc_data_raw = pbcseq %>%
  mutate(
    trt = case_match(
      trt,
      1 ~ "Treatment",
      0 ~ "Control"
    ),
    edema = case_match(
      edema,
      1.0 ~ "N Diuretics",
      0.5 ~ "Diuretics",
      0 ~ "None"
    ),
    edema = factor(
      edema, levels = c("None", "Diuretics", "N Diuretics")
    ),
    time_yr = round(day / 365, 3)) 

pbc_data = pbc_data_raw %>%
  mutate(
    ascites = ifelse(is.na(ascites), "Missing", ascites),
    hepato = ifelse(is.na(hepato), "Missing", hepato),
    spiders = ifelse(is.na(spiders), "Missing", spiders)
  ) %>%
  group_by(id) %>%
  mutate(
    alk.lag = lag(alk.phos),
    alk.med = median(alk.phos, na.rm = TRUE),
    alk.phos = ifelse(
      is.na(alk.phos), ifelse(is.na(alk.lag), alk.med, alk.lag), alk.phos
      )
  ) %>%
  mutate(
    plt.lag = lag(platelet),
    plt.med = median(platelet, na.rm = TRUE),
    platelet = ifelse(
      is.na(platelet), ifelse(is.na(plt.lag), plt.med, plt.lag), platelet
      )
  ) %>%
  ungroup() %>%
  select(-alk.lag, -alk.med, -plt.lag, -plt.med)

```

```{r}

pbc_data %>% 
  filter(trt == "Control") %>%
  group_by(id) %>%
  slice(1) %>%
  nrow()

```


## Part 2: Exploratory Data Analysis

```{r}

pbc_attributes = pbc_data %>%
  group_by(id) %>% 
  slice(1) 

pbc_attributes %>% pull(sex) %>% summary()
pbc_attributes %>% pull(age) %>% mean()
pbc_attributes %>% pull(age) %>% sd()
pbc_attributes %>% pull(stage) %>% factor() %>% summary()

```


```{r}

pbc_data %>%
  ggplot(aes(x = bili)) + 
  geom_histogram(fill = "lightblue", color = "black") +  
  theme_classic() + 
  labs(
    x = "Serum Bilirubin (mg/dL)",
    y = "Frequency"
  )

```


```{r}

bili_by_trt = pbc_data %>%
  ggplot(aes(x = trt, y = bili, fill = trt)) + 
  geom_boxplot() + 
  theme_classic() + 
  theme(legend.position = "none") + 
  labs(
    x = "",
    y = "Serum Bilirubin (mg/dL)"
  )

ggsave("bili_by_trt.pdf", plot = bili_by_trt, width = 5, height = 3.75, units = "in")

```

```{r}

pbc_data %>%
  filter(trt == "Control") %>%
  pull(bili) %>%
  summary()

pbc_data %>%
  filter(trt == "Treatment") %>%
  pull(bili) %>%
  summary()

```


```{r}

bili_spaghetti = pbc_data %>%
  ggplot(aes(x = day, y = bili, group = id, color = trt)) + 
  geom_line() + 
  theme_classic() + 
  labs(
    x = "Time Since First Study Visit (Days)",
    y = "Serum Bilirubin (mg/dL)"
  )

ggsave("bili_spaghetti.pdf", plot = bili_spaghetti, width = 5, height = 3.75, units = "in")

bili_spaghetti

```

```{r}

hist_study_visits = pbc_data %>%
  group_by(id) %>%
  summarize(visit_count = n()) %>%
  ggplot(aes(x = visit_count)) + 
  geom_histogram(fill = "lightblue", binwidth = 1, color = "black") + 
  theme_classic() + 
  labs(
    x = "Visit Count",
    y = "Frequency"
  )

ggsave("hist_study_visits.pdf", plot = hist_study_visits, width = 5, height = 3.75, units = "in")

```


## Part 3: Model Selection

```{r}

model_1 = lm(log(bili) ~ trt + age + sex + time_yr + trt*time_yr, data = pbc_data)

model_2 = lme(log(bili) ~ trt + age + sex + time_yr + trt*time_yr, random = ~1 | id, data = pbc_data, method = "ML")

model_3 = lme(log(bili) ~ trt + age + sex + time_yr + trt*time_yr, random = ~time_yr | id, data = pbc_data, method = "ML")

model_4 = lm(log(bili) ~ trt + age + sex + time_yr + trt*time_yr 
             + edema + albumin + ast + ascites + hepato + spiders + alk.phos,
             data = pbc_data)

model_5 = lme(log(bili) ~ trt + age + sex + time_yr + trt*time_yr 
              + edema + albumin + ast + ascites + hepato + spiders + alk.phos, 
              random = ~1 | id,
              data = pbc_data,
              method = "ML")

model_6 = lme(log(bili) ~ trt + age + sex + time_yr + trt*time_yr 
              + edema + albumin + ast + ascites + hepato + spiders + alk.phos, 
              random = ~time_yr | id,
              data = pbc_data,
              method = "ML")

model_7 = lm(log(bili) ~ trt + age + sex + time_yr + trt*time_yr 
             + edema + albumin + ast + ascites + hepato + spiders
             + platelet + protime,
             data = pbc_data)

model_8 = lme(log(bili) ~ trt + age + sex + time_yr + trt*time_yr 
              + edema + albumin + ast + ascites + hepato + spiders
              + platelet + protime, 
              random = ~1 | id,
              data = pbc_data,
              method = "ML")

model_9 = lme(log(bili) ~ trt + age + sex + time_yr + trt*time_yr 
              + edema + albumin + ast + ascites + hepato + spiders
              + platelet + protime, 
              random = ~time_yr | id,
              data = pbc_data,
              method = "ML")

```

```{r}

model_comp = data.frame(
  Model = c("Model 1", "Model 2", "Model 3", "Model 4", "Model 5", "Model 6", "Model 7", "Model 8", "Model 9"),
  Complexity = c(rep("Basic", 3), rep("+ Liver Variables", 3), rep("+ Liver and Blood Clotting Variables", 3)),
  Effects = rep(c("Fixed Only", "RI", "RI + RS"), 3),
  Log_Likelihood = c(
    logLik(model_1),
    logLik(model_2),
    logLik(model_3),
    logLik(model_4),
    logLik(model_5),
    logLik(model_6),
    logLik(model_7),
    logLik(model_8),
    logLik(model_9)
  ),
  AIC = c(
    AIC(model_1),
    AIC(model_2),
    AIC(model_3),
    AIC(model_4),
    AIC(model_5),
    AIC(model_6),
    AIC(model_7),
    AIC(model_8),
    AIC(model_9)
  )
) %>%
  mutate(
    Log_Likelihood = round(Log_Likelihood, 0),
    AIC = round(AIC, 0)
    )

model_comp_table = flextable(model_comp)

save_as_image(model_comp_table, path = "model_comp_table.png")

```

```{r}

model_i = lme(log(bili) ~ trt + age + sex + time_yr + trt*time_yr 
              + edema + albumin + ast + ascites + hepato + spiders,
              random = ~time_yr | id,
              data = pbc_data,
              method = "REML")

model_ii = lme(log(bili) ~ trt + age + sex + time_yr + trt*time_yr 
              + edema + albumin + ast + ascites + hepato + spiders,
              random = ~time_yr | id,
              data = pbc_data,
              correlation = corCompSymm(form = ~ 1 | id),
              method = "REML")

model_iii = lme(log(bili) ~ trt + age + sex + time_yr + trt*time_yr 
              + edema + albumin + ast + ascites + hepato + spiders,
              random = ~time_yr | id,
              data = pbc_data,
              correlation = corExp(form = ~time_yr + bili | id),
              method = "REML")

model_iv = lme(log(bili) ~ trt + age + sex + time_yr + trt*time_yr 
              + edema + albumin + ast + ascites + hepato + spiders,
              random = ~time_yr | id,
              data = pbc_data,
              correlation = corExp(form = ~time_yr + bili | id, nugget = TRUE),
              method = "REML")

model_v = lme(log(bili) ~ trt + age + sex + time_yr + trt*time_yr 
              + edema + albumin + ast + ascites + hepato + spiders,
              random = ~time_yr | id,
              data = pbc_data,
              weights = varIdent(form = ~1 | trt),
              control = lmeControl(maxIter = 200, msMaxIter = 200),
              method = "REML")

```

```{r}

corr_comp = data.frame(
  Residual_Correlation = c("Independent", "Exchangeable", "Exponential Spatial", "Exponential Spatial (+ nugget)", "Independent/Heteroskedastic"),
  Log_Likelihood = c(
    logLik(model_i),
    logLik(model_ii),
    logLik(model_iii),
    logLik(model_iv),
    logLik(model_v)
  ),
  AIC = c(
    AIC(model_i),
    AIC(model_ii),
    AIC(model_iii),
    AIC(model_iv),
    AIC(model_v)
  )
) %>%
  mutate(
    Log_Likelihood = round(Log_Likelihood, 0),
    AIC = round(AIC, 0)
    )

corr_comp_table = flextable(corr_comp)

save_as_image(corr_comp_table, path = "corr_comp_table.png")

```

```{r}

final_model = model_iv

VarCorr(final_model)

```


## Part 4: Model Evaluation and Diagnostics

```{r}

# make a fixed effects table

fixef = summary(final_model)$tTable %>%
  janitor::clean_names() %>%
  data.frame() %>%
  mutate(
    value = round(value, 4),
    std_error = round(std_error, 4),
    t_value = round(t_value, 3),
    p_value = round(p_value, 3),
    term = c(
      "Intercept",
      "Treatment",
      "Age",
      "Female Sex",
      "Time (years)",
      "Edema / Resp. to Diuretics",
      "Edema / Not Resp. to Diuretics",
      "Albumin",
      "AST",
      "Ascites",
      "Ascites - Missing",
      "Hepatomegaly",
      "Hepatomegaly - Missing",
      "Spider Angiomas",
      "Spider Angiomas - Missing",
      "Time : Treatment Interaction"
      )
    ) %>%
  select(term, value, std_error, p_value) %>%
  rename(Term = term, Value = value, SE = std_error, "P-Value" = p_value)

fixef_table = flextable(fixef)

save_as_image(fixef_table, path = "fixef_table.png")


```

```{r}

# get random effects

pbc_ranef = data.frame(
  ranef_complex = ranef(final_model)
) %>%
  rename(rand_int = ranef_complex..Intercept., rand_slope = ranef_complex.time_yr)

sd_ri = sd(pbc_ranef$rand_int)
sd_rs = sd(pbc_ranef$rand_slope)

```

```{r}

# get residuals

pbc_diag = pbc_data %>%
  mutate(stage1_resid = resid(final_model, type = "normalized")) %>%
  group_by(id) %>%
  arrange(id, time_yr) %>%
  mutate(
    resid_lag = lag(stage1_resid)
  ) %>%
  ungroup()

```


```{r}

# make diagnostic plots for the simple model

resid_plot = pbc_diag %>%
  ggplot(aes(x = time_yr, y = stage1_resid)) +
  geom_point() + 
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") + 
  theme(legend.position = "none") +
  theme_classic() + 
  labs(
    title = "Distributions of Residuals by Time",
    x = "Time From Baseline (Years)",
    y = "Normalized S1 Resid."
  ) + 
  theme(plot.title = element_text(size = 8)) + 
  theme(axis.title = element_text(size = 7))

resid_lag_plot = pbc_diag %>%
  ggplot(aes(x = resid_lag, y = stage1_resid)) + 
  geom_point() + 
  geom_smooth(se = FALSE) + 
  theme_classic() + 
  labs(
    title = "Residuals vs. Lagged Residuals",
    x = "Lagged Residuals",
    y = "Normalized S1 Resid."
  ) + 
  theme(plot.title = element_text(size = 8)) + 
  theme(axis.title = element_text(size = 7))

qq_plot_resid = pbc_diag %>%
  ggplot(aes(sample = stage1_resid)) +
  stat_qq() + 
  stat_qq_line() + 
  theme_classic() +
  labs(
    title = "Q-Q Plot of Stage 1 Residuals",
    x = "Theoretical Quantities",
    y = "Sample Quantities"
  ) + 
  theme(plot.title = element_text(size = 8)) + 
  theme(axis.title = element_text(size = 7))

qq_plot_ranef = pbc_ranef %>%
  ggplot(aes(sample = rand_int)) +
  stat_qq() + 
  stat_qq_line() + 
  theme_classic() +
  labs(
    title = "Q-Q Plot of Random Intercepts",
    x = "Theoretical Quantities",
    y = "Sample Quantities"
  ) + 
  theme(plot.title = element_text(size = 8)) + 
  theme(axis.title = element_text(size = 7))

qq_plot_ransl = pbc_ranef %>%
  ggplot(aes(sample = rand_slope)) +
  stat_qq() + 
  stat_qq_line() + 
  theme_classic() +
  labs(
    title = "Q-Q Plot of Random Slopes",
    x = "Theoretical Quantities",
    y = "Sample Quantities"
  ) + 
  theme(plot.title = element_text(size = 8)) + 
  theme(axis.title = element_text(size = 7))

diag_plots = plot_grid(plotlist = list(
  resid_plot, 
  resid_lag_plot, 
  qq_plot_resid,
  qq_plot_ranef,
  qq_plot_ransl),
  nrow = 3,
  ncol = 2
  )

diag_plots

save_plot("diag_plots.png", diag_plots, base_width = 5, base_height = 3.75)

```

## Missing Data Check

```{r}

length(pbc_data_raw$ascites[is.na(pbc_data_raw$ascites)])
length(pbc_data_raw$hepato[is.na(pbc_data_raw$hepato)])
length(pbc_data_raw$spiders[is.na(pbc_data_raw$spiders)])
length(pbc_data_raw$alk.phos[is.na(pbc_data_raw$alk.phos)])
length(pbc_data_raw$platelet[is.na(pbc_data_raw$platelet)])
length(pbc_data_raw$protime[is.na(pbc_data_raw$protime)])

```
